version: '3.8'

services:
  kartverketprosjekt:
    image: ${DOCKER_REGISTRY-}Nettside
    build:
      context: .
      dockerfile: Nettside/Dockerfile
    ports:
      - "8080:8080"  # Maps host port 8080 to container port 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=localhost\MSSQLSERVER01;Database=UserApp;User ID=sa;Trusted_Connection=True;MultipleActiveResultSets=true;TrustServerCertificate=true
    depends_on:
      - sqlserver  # Corrected to depend on sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"  # Default port for SQL Server
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - backend

volumes:
  sqlserver_data:  # Volume to persist SQL Server data

networks:
  backend:  # Network for services to communicate with each other
